arrowParens: always
bracketSameLine: true
bracketSpacing: true
endOfLine: auto
printWidth: 100
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
plugins:
  - prettier-plugin-tailwindcss
